export const apiRes = {
  1: [
    {
      congestion_level: "Low",
      direction: "E",
      lane: "00",
      vehicle_class_code: "VC11",
    },
    {
      congestion_level: "High",
      direction: "N",
      lane: "LANE10",
      vehicle_class_code: "VC10",
    },
    {
      congestion_level: "Medium",
      direction: "N",
      lane: "LANE11",
      vehicle_class_code: "VC10",
    },
    {
      congestion_level: "Low",
      direction: "S",
      lane: "LANE15",
      vehicle_class_code: "VC10",
    },
    {
      congestion_level: "High",
      direction: "S",
      lane: "LANE16",
      vehicle_class_code: "VC10",
    },
    {
      congestion_level: "Medium",
      direction: "S",
      lane: "LANE2",
      vehicle_class_code: "VC10",
    },
    {
      congestion_level: "Low",
      direction: "N",
      lane: "LANE21",
      vehicle_class_code: "VC10",
    },
    {
      congestion_level: "High",
      direction: "N",
      lane: "LANE22",
      vehicle_class_code: "VC10",
    },
    {
      congestion_level: "Medium",
      direction: "N",
      lane: "LANE23",
      vehicle_class_code: "VC10",
    },
    {
      congestion_level: "Low",
      direction: "N",
      lane: "LANE24",
      vehicle_class_code: "VC10",
    },
    {
      congestion_level: "High",
      direction: "N",
      lane: "LANE25",
      vehicle_class_code: "VC10",
    },
    {
      congestion_level: "Medium",
      direction: "S",
      lane: "LANE29",
      vehicle_class_code: "VC10",
    },
    {
      congestion_level: "Low",
      direction: "S",
      lane: "LANE3",
      vehicle_class_code: "VC10",
    },
    {
      congestion_level: "High",
      direction: "S",
      lane: "LANE30",
      vehicle_class_code: "VC10",
    },
    {
      congestion_level: "Medium",
      direction: "S",
      lane: "LANE31",
      vehicle_class_code: "VC10",
    },
    {
      congestion_level: "Low",
      direction: "S",
      lane: "LANE32",
      vehicle_class_code: "VC10",
    },
    {
      congestion_level: "High",
      direction: "S",
      lane: "LANE4",
      vehicle_class_code: "VC10",
    },
    {
      congestion_level: "Medium",
      direction: "N",
      lane: "LANE9",
      vehicle_class_code: "VC10",
    },
  ],
  2: [
    {
      congestion_level: "Medium",
      direction: "E",
      lane: "00",
      vehicle_class_code: "VC4",
    },
    {
      congestion_level: "Low",
      direction: "N",
      lane: "LANE10",
      vehicle_class_code: "VC11",
    },
    {
      congestion_level: "High",
      direction: "N",
      lane: "LANE11",
      vehicle_class_code: "VC12",
    },
    {
      congestion_level: "Medium",
      direction: "S",
      lane: "LANE15",
      vehicle_class_code: "VC11",
    },
    {
      congestion_level: "Low",
      direction: "S",
      lane: "LANE16",
      vehicle_class_code: "VC10",
    },
    {
      congestion_level: "High",
      direction: "S",
      lane: "LANE2",
      vehicle_class_code: "VC10",
    },
    {
      congestion_level: "Medium",
      direction: "N",
      lane: "LANE21",
      vehicle_class_code: "VC10",
    },
    {
      congestion_level: "Low",
      direction: "N",
      lane: "LANE22",
      vehicle_class_code: "VC10",
    },
    {
      congestion_level: "High",
      direction: "N",
      lane: "LANE23",
      vehicle_class_code: "VC10",
    },
    {
      congestion_level: "Medium",
      direction: "N",
      lane: "LANE24",
      vehicle_class_code: "VC10",
    },
    {
      congestion_level: "Low",
      direction: "N",
      lane: "LANE25",
      vehicle_class_code: "VC10",
    },
    {
      congestion_level: "High",
      direction: "S",
      lane: "LANE29",
      vehicle_class_code: "VC10",
    },
    {
      congestion_level: "Medium",
      direction: "S",
      lane: "LANE3",
      vehicle_class_code: "VC10",
    },
    {
      congestion_level: "Low",
      direction: "S",
      lane: "LANE30",
      vehicle_class_code: "VC10",
    },
    {
      congestion_level: "High",
      direction: "S",
      lane: "LANE31",
      vehicle_class_code: "VC10",
    },
    {
      congestion_level: "Medium",
      direction: "S",
      lane: "LANE32",
      vehicle_class_code: "VC10",
    },
    {
      congestion_level: "Low",
      direction: "S",
      lane: "LANE4",
      vehicle_class_code: "VC10",
    },
    {
      congestion_level: "High",
      direction: "N",
      lane: "LANE9",
      vehicle_class_code: "VC10",
    },
  ],
  3: [
    {
      congestion_level: "Low",
      direction: "E",
      lane: "00",
      vehicle_class_code: "VC7",
    },
    {
      congestion_level: "Medium",
      direction: "S",
      lane: "1",
      vehicle_class_code: "VC10",
    },
    {
      congestion_level: "High",
      direction: "S",
      lane: "10",
      vehicle_class_code: "VC4",
    },
    {
      congestion_level: "Medium",
      direction: "N",
      lane: "11",
      vehicle_class_code: "VC4",
    },
    {
      congestion_level: "Low",
      direction: "N",
      lane: "12",
      vehicle_class_code: "VC10",
    },
    {
      congestion_level: "High",
      direction: "N",
      lane: "13",
      vehicle_class_code: "VC10",
    },
    {
      congestion_level: "Medium",
      direction: "N",
      lane: "14",
      vehicle_class_code: "VC10",
    },
    {
      congestion_level: "Low",
      direction: "N",
      lane: "15",
      vehicle_class_code: "VC11",
    },
    {
      congestion_level: "High",
      direction: "N",
      lane: "16",
      vehicle_class_code: "VC10",
    },
    {
      congestion_level: "Medium",
      direction: "N",
      lane: "17",
      vehicle_class_code: "VC10",
    },
    {
      congestion_level: "Low",
      direction: "N",
      lane: "18",
      vehicle_class_code: "VC11",
    },
    {
      congestion_level: "High",
      direction: "N",
      lane: "19",
      vehicle_class_code: "VC10",
    },
    {
      congestion_level: "Medium",
      direction: "S",
      lane: "2",
      vehicle_class_code: "VC10",
    },
    {
      congestion_level: "Low",
      direction: "N",
      lane: "20",
      vehicle_class_code: "VC10",
    },
    {
      congestion_level: "High",
      direction: "S",
      lane: "3",
      vehicle_class_code: "VC10",
    },
    {
      congestion_level: "Medium",
      direction: "N",
      lane: "31",
      vehicle_class_code: "VC10",
    },
    {
      congestion_level: "Low",
      direction: "N",
      lane: "32",
      vehicle_class_code: "VC20",
    },
    {
      congestion_level: "High",
      direction: "N",
      lane: "33",
      vehicle_class_code: "VC4",
    },
    {
      congestion_level: "Medium",
      direction: "S",
      lane: "4",
      vehicle_class_code: "VC10",
    },
    {
      congestion_level: "Low",
      direction: "S",
      lane: "5",
      vehicle_class_code: "VC10",
    },
    {
      congestion_level: "High",
      direction: "S",
      lane: "6",
      vehicle_class_code: "VC12",
    },
    {
      congestion_level: "Medium",
      direction: "S",
      lane: "7",
      vehicle_class_code: "VC10",
    },
    {
      congestion_level: "Low",
      direction: "S",
      lane: "8",
      vehicle_class_code: "VC10",
    },
    {
      congestion_level: "High",
      direction: "S",
      lane: "9",
      vehicle_class_code: "VC10",
    },
  ],
  4: [
    {
      congestion_level: "Low",
      direction: "E",
      lane: "00",
      vehicle_class_code: "VC7",
    },
    {
      congestion_level: "Medium",
      direction: "S",
      lane: "1",
      vehicle_class_code: "VC10",
    },
    {
      congestion_level: "High",
      direction: "S",
      lane: "10",
      vehicle_class_code: "VC4",
    },
    {
      congestion_level: "Medium",
      direction: "N",
      lane: "11",
      vehicle_class_code: "VC4",
    },
    {
      congestion_level: "Low",
      direction: "N",
      lane: "12",
      vehicle_class_code: "VC10",
    },
    {
      congestion_level: "High",
      direction: "N",
      lane: "13",
      vehicle_class_code: "VC10",
    },
    {
      congestion_level: "Medium",
      direction: "N",
      lane: "14",
      vehicle_class_code: "VC10",
    },
    {
      congestion_level: "Low",
      direction: "N",
      lane: "15",
      vehicle_class_code: "VC11",
    },
    {
      congestion_level: "High",
      direction: "N",
      lane: "16",
      vehicle_class_code: "VC10",
    },
    {
      congestion_level: "Medium",
      direction: "N",
      lane: "17",
      vehicle_class_code: "VC10",
    },
    {
      congestion_level: "Low",
      direction: "N",
      lane: "18",
      vehicle_class_code: "VC11",
    },
    {
      congestion_level: "High",
      direction: "N",
      lane: "19",
      vehicle_class_code: "VC10",
    },
    {
      congestion_level: "Medium",
      direction: "S",
      lane: "2",
      vehicle_class_code: "VC10",
    },
    {
      congestion_level: "Low",
      direction: "N",
      lane: "20",
      vehicle_class_code: "VC10",
    },
    {
      congestion_level: "High",
      direction: "S",
      lane: "3",
      vehicle_class_code: "VC10",
    },
    {
      congestion_level: "Medium",
      direction: "N",
      lane: "31",
      vehicle_class_code: "VC10",
    },
    {
      congestion_level: "Low",
      direction: "N",
      lane: "32",
      vehicle_class_code: "VC20",
    },
    {
      congestion_level: "High",
      direction: "N",
      lane: "33",
      vehicle_class_code: "VC4",
    },
    {
      congestion_level: "Medium",
      direction: "S",
      lane: "4",
      vehicle_class_code: "VC10",
    },
    {
      congestion_level: "Low",
      direction: "S",
      lane: "5",
      vehicle_class_code: "VC10",
    },
    {
      congestion_level: "High",
      direction: "S",
      lane: "6",
      vehicle_class_code: "VC12",
    },
    {
      congestion_level: "Medium",
      direction: "S",
      lane: "7",
      vehicle_class_code: "VC10",
    },
    {
      congestion_level: "Low",
      direction: "S",
      lane: "8",
      vehicle_class_code: "VC10",
    },
    {
      congestion_level: "High",
      direction: "S",
      lane: "9",
      vehicle_class_code: "VC10",
    },
  ],
};
