export const apiRes = {
  merchant_name: "ELECTRONIC  CITY Phase 1",
  predictions: [
    {
      congestion_level: "Low",
      direction: "E",
      lane: "00",
      vehicle_class_code: "VC11",
    },
    {
      congestion_level: "High",
      direction: "N",
      lane: "LANE10",
      vehicle_class_code: "VC10",
    },
    {
      congestion_level: "High",
      direction: "N",
      lane: "LANE11",
      vehicle_class_code: "VC10",
    },
    {
      congestion_level: "High",
      direction: "S",
      lane: "LANE15",
      vehicle_class_code: "VC10",
    },
    {
      congestion_level: "High",
      direction: "S",
      lane: "LANE16",
      vehicle_class_code: "VC10",
    },
    {
      congestion_level: "High",
      direction: "S",
      lane: "LANE2",
      vehicle_class_code: "VC10",
    },
    {
      congestion_level: "High",
      direction: "N",
      lane: "LANE21",
      vehicle_class_code: "VC10",
    },
    {
      congestion_level: "High",
      direction: "N",
      lane: "LANE22",
      vehicle_class_code: "VC10",
    },
    {
      congestion_level: "High",
      direction: "N",
      lane: "LANE23",
      vehicle_class_code: "VC10",
    },
    {
      congestion_level: "High",
      direction: "N",
      lane: "LANE24",
      vehicle_class_code: "VC10",
    },
    {
      congestion_level: "High",
      direction: "N",
      lane: "LANE25",
      vehicle_class_code: "VC10",
    },
    {
      congestion_level: "High",
      direction: "S",
      lane: "LANE29",
      vehicle_class_code: "VC10",
    },
    {
      congestion_level: "High",
      direction: "S",
      lane: "LANE3",
      vehicle_class_code: "VC10",
    },
    {
      congestion_level: "High",
      direction: "S",
      lane: "LANE30",
      vehicle_class_code: "VC10",
    },
    {
      congestion_level: "High",
      direction: "S",
      lane: "LANE31",
      vehicle_class_code: "VC10",
    },
    {
      congestion_level: "High",
      direction: "S",
      lane: "LANE32",
      vehicle_class_code: "VC10",
    },
    {
      congestion_level: "High",
      direction: "S",
      lane: "LANE4",
      vehicle_class_code: "VC10",
    },
    {
      congestion_level: "High",
      direction: "N",
      lane: "LANE9",
      vehicle_class_code: "VC10",
    },
  ],
};
